name: DownloadArtifactFromDataFactoryCICDPipeline-$(Date:yyyyMMdd)$(Rev:.r)

trigger: none # Manual trigger

pool:
  vmImage: "windows-latest"

parameters:
- name: PipelineID
  type: number
  default: 1
# Pipeline ID of the other pipeline you want to grab the artifact from.

jobs:
- job: GetLatestSuccessfulRunIDAndDownloadArtifact 
  # Automatically gets the latest successful run ID of the other pipeline (PipelineID parameter) and will download the artifact.
  steps:
  - bash: |
      LatestSuccessfulRunID=$(az pipelines build list --definition-ids ${{ parameters.PipelineID }} --detect true --org "https://dev.azure.com/DataEngineeringWithNick" --project "AzurePipelineDataFactoryCICD" --result succeeded --status completed --top 1 --query "reverse(sort_by(@, &finishTime)) | [0].id")
      echo "The latest successful pipeline RunID is: $LatestSuccessfulRunID"
      echo "##vso[task.setvariable variable=RunID;]$LastestSuccessfulRunID"
    displayName: "Get Lastest Successful Pipeline RunID"
    env:
      AZURE_DEVOPS_EXT_PAT: $(System.AccessToken)
    
  - task: DownloadPipelineArtifact@2
    displayName: "Download The ADF Artifact"
    inputs:
      buildType: "specific"
      project: "AzurePipelineDataFactoryCICD"
      pipeline: ${{ parameters.PipelineID }}
      runId: $(RunID) # Uses the variable created in the previous "Get Latest Successful Pipeline RunID" task above.
      artifactName: "ADFArtifact"
      targetpath: "$(Pipeline.Workspace)/MyPipelineFolder"
  
  - task: CmdLine@2
    displayName: "List Contents of the ADF Artifact"
    inputs:
      script: dir
      workingDirectory: "$(Pipeline.Workspace)/MyPipelineFolder" 

